python3 -m pip install opendatasets --upgrade --user
python3 -m pip install seaborn --upgrade --user
python3 -m pip install opencv-python-headless --upgrade --user
python3 -m pip install numpy --upgrade --user
python3 -m pip install pandas --upgrade --user
python3 -m pip install matplotlib --upgrade --user
python3 -m pip install scikit-learn --upgrade --user
python3 -m pip install tensorflow --upgrade --user
python3 -m pip install tensorflow_hub --upgrade --user
python3 -m pip install flask --upgrade --user
python3 -m pip install flask_cors --upgrade --user