# -*- coding: utf-8 -*-
"""Larissa's Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H2zSYh3-sSH3VTx4PQKrRcsv4lFFkraz
"""

import sys
sys.path.insert(0, '..')
import serveUnit

import os
import seaborn as sns
import numpy as np
import tensorflow as tf
import tensorflow_hub as hub 
import matplotlib.pyplot as plt
import sklearn
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
import opendatasets as od
import time
from tensorflow import keras

model = keras.models.load_model("./lastModel.h5")

def classify(image):
    y_pred = model(np.array([image]))
    res = "[" + ",".join(str(y_pred).split("[[")[1].split("]]")[0].split(" ")) + "]"
    res = res.replace(",,", ",")
    res = res.replace(",,", ",")
    res = res.replace(",,", ",")

    if (res[-1] == ","):
        res = res[:-1]
    if (res[-1] == ","):
        res = res[:-1]
    if (res[-1] == ","):
        res = res[:-1]

    return res # yup, i just did that. if you know how tensors work, please fix :)

serveUnit.subscribe(classify)

serveUnit.start(port=5005)